config/routes.rb
Rails.application.routes.draw do
  get '/tasks', to: 'tasks#index', as: :index
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def edit
  end

  def update
    params["task"]["completed"] == "1" ? @task.completed = true : @task.completed = false
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.full_messages.any? %>
      <%  @task.errors.full_messages.each do |msg| %>
        <p class='text-danger'><%= msg %></p>
      <% end %>
    <% end %>
    <div class="form-group">
      <%= f.label :title%>
      <%= f.text_field :title, class: 'form-control'   %>
    </div>
    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_area :details, class: 'form-control'   %>
    </div>
    <div class="form-group form-check">
      <%= f.check_box :completed %>
      <%= f.label :completed, "Mark as complete" %>
    </div>
    <%= f.submit 'Update Task', :class => 'btn btn-primary' %>
  <% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit <%= @task.title %></h1>
  <%= render 'tasks/form' %>
  <hr>
  <%= link_to '⏮ back to list', tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container">
<h1>My tasks</h1>
<% @tasks.each do |task| %>
  <% if task.completed %>
  <p><i class="fas fa-check-square"></i> <%= link_to task.title, task_path(task) %> - <%= link_to '🗑', task_path(task), method: :delete, data: { confirm: "Do you really want to delete the #{task.title} task?"} %></p>
  <% else %>
  <p><i class="fas fa-stop"></i> <%= link_to task.title, task_path(task) %> -  <%= link_to '🗑', task_path(task), method: :delete, data: { confirm: "Do you really want to delete the #{task.title} task?"} %></p>
  <% end %>
<% end %>
<hr>
<%= link_to '📄 Create a task', new_task_path %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Add a Task</h1>
  <%= render 'tasks/form' %>
  <hr>
  <%= link_to '⏮ back to list', tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
    <h1><%= @task.title %></h1>
  <div class="alert alert-secondary mt-3" role="alert">
    <%= @task.details %>
  </div>
  <% if @task.completed %>
    <p><i class="fas fa-check-square"></i> This taks is completed</p>
  <% else %>
    <p><i class="fas fa-stop"></i> This task is not completed yet</p>
  <% end %>
  <div class="d-flex justify-content-between mt-3">
    <%= link_to 'Back to list', index_path, :class => 'btn btn-primary' %>
    <%= link_to 'Edit task', edit_path, :class => 'btn btn-danger' %>
  </div>
</div>